# Generated by Django 4.2.7 on 2023-11-27 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='detail',
        ),
        migrations.AddField(
            model_name='applicant',
            name='applicant_name',
            field=models.CharField(default='Applicant', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='graduate_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='phone_number',
            field=models.BigIntegerField(default='20000000'),
            preserve_default=False,
        ),
    ]
