# Generated by Django 4.2.7 on 2023-11-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_remove_applicant_detail_applicant_applicant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='graduate_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
