# Generated by Django 4.2.7 on 2023-11-27 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_applicant_graduate_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
